# Generated by Django 6.0.6 on 2026-06-28 06:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0013_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="شماره تلفن همراه"
                    ),
                ),
                (
                    "avatar",
                    models.FileField(
                        upload_to="user/avatar", verbose_name="پروفایل کاربری"
                    ),
                ),
                (
                    "linkedin_link",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="لینک پروفایل لینکدین",
                    ),
                ),
                (
                    "telegram_link",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="لینک پروفایل تلگرام",
                    ),
                ),
                (
                    "instagram_link",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="لینک پروفایل اینستاگرام",
                    ),
                ),
                (
                    "x_link",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="لینک پروفایل ایکس",
                    ),
                ),
                (
                    "bale_link",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="لینک پروفایل بله",
                    ),
                ),
                (
                    "eitaa_link",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="لینک پروفایل ایتا",
                    ),
                ),
                (
                    "skills",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="مهارت ها"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="درباره من"),
                ),
                ("position", models.CharField(max_length=255, verbose_name="سمت")),
                (
                    "national_code",
                    models.CharField(max_length=11, verbose_name="کدملی"),
                ),
                (
                    "birth_day",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="آیا مدیر باشد؟"),
                ),
                (
                    "is_admin_technical",
                    models.BooleanField(
                        default=False, verbose_name="آیا مدیر فنی باشد؟"
                    ),
                ),
                (
                    "is_admin_product",
                    models.BooleanField(
                        default=False, verbose_name="آیا مدیر محصول باشد؟"
                    ),
                ),
                (
                    "is_admin_finance",
                    models.BooleanField(
                        default=False, verbose_name="آیا مدیر مالی باشد؟"
                    ),
                ),
                (
                    "is_admin_creator",
                    models.BooleanField(
                        default=False, verbose_name="آیا مدیر تولیدمحتوا باشد؟"
                    ),
                ),
                (
                    "is_employee",
                    models.BooleanField(default=True, verbose_name="آیا کارمند باشد؟"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
